### PR TITLE
Reduce Dockerfile layers and fix API_KEY not being set correctly

### PR DESCRIPTION
**Pull request by dennorske**
Removing apt lists + making all APT related commands in one layer will speed up + reduce layer size.

### CODE REVIEW

**Comment by dennorske** [comment]
Perhaps we can use ghcr to host the image? 
https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry

**Comment by MichaelBelgium** [comment]
> Perhaps we can use ghcr to host the image? https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry

Thats something else than just doing `docker-compose` ? 

EDIT: okay i have trouble understanding that page 😂

**Review by MichaelBelgium — APPROVED** [review]

**Comment by dennorske** [comment]
It would be that instead of relying on:
1. cloning the repo
2. building the docker image
3. starting the docker-compose service (which also builds it xd) 

people can do:
1. docker directly (either with or without docker-compose) 

for instance, imagine something along these lines;

`docker run -e API_KEY=12345abcd -p 80:80 ghcr.io/michaelbelgium/youtube-api:latest` 

Something in the registry I linked, will already be a "built" image, so other can download and use directly :) I hope that makes sense.

It is a very minor thing, so not really "needed" but a nice-to-have kind of thing

**Comment by dennorske** [comment]
@MichaelBelgium 
Do not merge yet, I found something that might have been an issue for a while (which I can fix)
Hmm I was running a very old version of the API I noticed. Under testing now, I see that the environment variable `API_KEY` is not being set correctly with the logic you added.

`Uncaught Error: Undefined class constant 'API_KEY' in /var/www/html/search.php:19`

The code the sed part in the dockerfile adds looks like this in `src/Config.php`:

```php
 //================ search options ================

    /**
     * The maximum search results to show
     */
    const MAX_RESULTS = 10;

    /**
     * Youtube api key
     *
     * Note: required for searching on youtube
     */
    public function _constructor() { $this->API_KEY = getenv("API_KEY"); }
}

``` 

If I knew PHP, I would be able to perhaps fix this, but not sure why you are setting it in the constructor (I believe it has to do with it being a constant?) 

Could you give me the correct code to use and I will modify this PR to address that as well :) 

Also psst can I have write access to the repo as well?

**Comment by MichaelBelgium** [comment]
It should be

```
public function _constructor() { self::API_KEY = getenv("API_KEY"); }
```

That should work

**Comment by dennorske** [comment]
> self::API_KEY = getenv("API_KEY");

sadly not working, resulting config is; 

```php
<?php

namespace MichaelBelgium\YoutubeConverter;

class Config
{
    //================ convert options ================

    /**
     * The folder where downloaded songs will be placed in
     * 
     * Note: make sure the webserver has permissions to write in this folder
     */
    const DOWNLOAD_FOLDER = "download/";

    /**
     * The maximum allowed video length to download (in seconds).
     * 
     * Set to 0 to disable
     */
    const DOWNLOAD_MAX_LENGTH = 0;

    /**
     * Enable logging
     * 
     * Note: this also enables the page /logs with an overview of all songs that have been converted
     */
    const LOG = false;

    //================ search options ================

    /**
     * The maximum search results to show
     */
    const MAX_RESULTS = 10;

    /**
     * Youtube api key
     * 
     * Note: required for searching on youtube
     */
    public function _constructor() { self::API_KEY = getenv("API_KEY"); }
}
```
The error it returns is 

`
image

 `<b>Parse error</b>:  syntax error, unexpected '=' in <b>/var/www/html/src/Config.php</b> on line <b>42</b><br />`


Do you have an opportunity to check out + test ?

**Comment by MichaelBelgium** [comment]
Wait but the constant is gone in your file

https://github.com/MichaelBelgium/Youtube-API/blob/abbf853bf0062af76429efe5d394e434b387bbb3/src/Config.php#L37-L42

And the constructor will never be called because I don't do `new Config()` anywhere.
What if you do `const API_KEY = getenv("API_KEY");`

~~Also where does `getenv` even come from~~

EDIT: [oh nevermind](https://www.php.net/manual/en/function.getenv.php)

EDIT 2:  using getenv in a constant won't work either. Need another solution but not sure which yet.
API_KEY constant can't be changed but in config itself, as a string variable. Not a function or anything (like getenv())

EDIT 3:  You're gonna have to get the value of the environment variable "API_KEY" in `Dockerfile` and then insert that value between the quotes of `const API_KEY = ""` with sed or any other linux command

**Comment by dennorske** [comment]
Good call, thanks for the idea!

Will do that and put between the quotes. I messed around a bit with 0 knowledge and also figured that constants could not be assigned by another variable value (like wtf? xd) 

Will proceed with that and let you know when its working :+1:

**Comment by MichaelBelgium** [comment]
> also figured that constants could not be assigned by another variable value (like wtf? xd)

Haha yeah, its a constant for something! I Basicly changed the config variables to constants because there's no reason those variables should change while the "code is running"

> Will proceed with that and let you know when its working 👍

Alright 👍

**Comment by dennorske** [comment]
I have revamped it a bit, been testing fanatically in order to iron out any issues. I also updated the readme and made sure in-line comments are added for better understanding.

It is ready to be merged from my end :+1:

**Review by MichaelBelgium — APPROVED** [review]

**Pull request merged**
